/**
 * Shared workspace schema for HCP Terraform API responses
 */
export const workspaceSchema = {
  type: "object" as const,
  properties: {
    id: { type: "string" },
    type: { type: "string" },
    name: { type: "string" },
    description: { type: "string" },
    environment: { type: "string" },
    autoApply: { type: "boolean" },
    autoApplyRunTrigger: { type: "boolean" },
    allowDestroyPlan: { type: "boolean" },
    assessmentsEnabled: { type: "boolean" },
    autoDestroyAt: { type: "string" },
    autoDestroyStatus: { type: "string" },
    autoDestroyActivityDuration: { type: "string" },
    inheritsProjectAutoDestroy: { type: "boolean" },
    createdAt: { type: "string" },
    updatedAt: { type: "string" },
    latestChangeAt: { type: "string" },
    lastAssessmentResultAt: { type: "string" },
    locked: { type: "boolean" },
    lockedReason: { type: "string" },
    oauthClientName: { type: "string" },
    operations: { type: "boolean" },
    executionMode: { type: "string" },
    fileTriggersEnabled: { type: "boolean" },
    globalRemoteState: { type: "boolean" },
    applyDurationAverage: { type: "number" },
    planDurationAverage: { type: "number" },
    policyCheckFailures: { type: "number" },
    queueAllRuns: { type: "boolean" },
    resourceCount: { type: "number" },
    runFailures: { type: "number" },
    source: { type: "string" },
    sourceName: { type: "string" },
    sourceUrl: { type: "string" },
    speculativeEnabled: { type: "boolean" },
    structuredRunOutputEnabled: { type: "boolean" },
    tagNames: { type: "array", items: { type: "string" } },
    terraformVersion: { type: "string" },
    triggerPrefixes: { type: "array", items: { type: "string" } },
    vcsRepo: { type: "object" },
    vcsRepoIdentifier: { type: "string" },
    workingDirectory: { type: "string" },
    workspaceKpisRunsCount: { type: "number" },
    unarchivedWorkspaceChangeRequestsCount: { type: "number" },
    settingOverwrites: { type: "object" },
    actions: {
      type: "object",
      properties: {
        isDestroyable: { type: "boolean" },
      },
    },
    permissions: {
      type: "object",
      properties: {
        canUpdate: { type: "boolean" },
        canDestroy: { type: "boolean" },
        canQueueRun: { type: "boolean" },
        canReadRun: { type: "boolean" },
        canReadVariable: { type: "boolean" },
        canUpdateVariable: { type: "boolean" },
        canReadStateVersions: { type: "boolean" },
        canReadStateOutputs: { type: "boolean" },
        canCreateStateVersions: { type: "boolean" },
        canQueueApply: { type: "boolean" },
        canLock: { type: "boolean" },
        canUnlock: { type: "boolean" },
        canForceUnlock: { type: "boolean" },
        canReadSettings: { type: "boolean" },
        canManageTags: { type: "boolean" },
        canManageRunTasks: { type: "boolean" },
        canForceDelete: { type: "boolean" },
        canManageAssessments: { type: "boolean" },
        canManageEphemeralWorkspaces: { type: "boolean" },
        canReadAssessmentResults: { type: "boolean" },
        canQueueDestroy: { type: "boolean" },
      },
    },
    agentPool: { type: "object" },
    currentConfigurationVersion: { type: "object" },
    currentRun: { type: "object" },
    currentStateVersion: { type: "object" },
    currentAssessmentResult: { type: "object" },
    organization: { type: "object" },
    outputs: { type: "array", items: { type: "object" } },
    project: { type: "object" },
    readme: { type: "object" },
    sshKey: { type: "object" },
    lockedBy: { type: "object" },
    vars: { type: "array", items: { type: "object" } },
  },
  required: ["id", "type", "name"],
};
